### ISSUE TITLE
Calling ->default of configfile attribute violates calling convention

### ISSUE THREAD

**Issue by rehsack** [mjgardner/moosex-app-cmd#2]
While trying to avoid users must specify --configfile when invoking an MX::App::Cmd application, I tried to implement a default sub which searches in typical config dirs for configuration.

To allow overriding search routine, I called it from the default sub as described at http://search.cpan.org/~doy/Moose-2.0603/lib/Moose/Manual/Attributes.pod#Default_and_builder_methods using

has '+configfile' => (
 default => sub { $_[0]->_find_config_file }
);

what failed with:

Can't call method "_find_config_file" on an undefined value at ...

Find a patch containing a test at http://paste.scsys.co.uk/207985 (I would attach it, but I can't find where).

**Comment by rehsack** [comment]
As recommended by mst I uploaded it to https://gist.github.com/3749113

**Comment by rehsack** [comment]
According to RT#79912 (https://rt.cpan.org/Ticket/Display.html?id=79912) I modified the patch.
Please see https://gist.github.com/3800122

**Comment by karenetheridge** [comment]
I agree that MooseX::ConfigFromFile could handle things a bit better here.... Changing the API would have an effect on anything that consumes it however (e.g. MooseX::SimpleConfig), so we need to take care with changes.

Please feel free to poke me again about this in a few days.

**Comment by rehsack** [comment]
2012/10/4 Karen Etheridge notifications@github.com

> I agree that MooseX::ConfigFromFile could handle things a bit better here.... Changing the API would have an effect on anything that consumes it however (e.g. MooseX::SimpleConfig), so we need to take care with changes.
> 
> Please feel free to poke me again about this in a few days.
> 
> —
> Reply to this email directly or view it on GitHub.

Hi Karen,

This is regarded MooseX::App::Cmd, right?
And there is a calling convention for attr->default() described in
http://search.cpan.org/dist/Moose/lib/Class/MOP/Attribute.pm

$attr->default($instance)
    The $instance argument is optional. If you don't pass it, the
return value for this method is exactly what was passed to the
constructor, either a simple scalar or a subroutine reference.
    If you do pass an $instance and the default is a subroutine
reference, then the reference is called as a method on the $instance
and the generated value is returned.

and from http://search.cpan.org/~doy/Moose-2.0604/lib/Moose/Manual/Attributes.pod#Default_and_builder_methods

... Moose will throw an error if you pass a bare non-subroutine
reference as the default.

So MooseX::App::Cmd::Command violates Moose-API for attributes.

The patch shall fix only that.

/Jens

**Comment by karenetheridge** [comment]
The changes that were requested in https://rt.cpan.org/Ticket/Display.html?id=79746 are now released.  Note that  MooseX::App::Cmd does not pass tests with MooseX::ConfigFromFile 0.08, as it does not provide an invocant when the default sub is called.

Calling the default sub directly is no longer necessary. Use a _get_default_configfile method.

Also I'm a bit surprised that you need to override _process_args. Just composing MooseX::Getopt should work, should it not?

**Comment by rehsack** [comment]
That why the patch in this thread. Please refer to Moose requirements at http://search.cpan.org/%7Edoy/Moose-2.0603/lib/Moose/Manual/Attributes.pod#Default_and_builder_methods

I do not override _process_args - I patched the wrong calling of a builder method.

**Comment by karenetheridge** [comment]
rehsack: I meant "you" in the "author of MooseX::App::Cmd" sense, not you personally :)

Where does this issue stand, now that there are new versions of MooseX::Getopt and MooseX::ConfigFromFile?

**Comment by oeuftete** [comment]
Related, I made a [pull request](https://github.com/mjgardner/moosex-app-cmd/pull/3) which simply makes it so the test passes... I see now it reproduces one line of rehsack's patch (I saw this issue after) and I don't think it addresses the real issues.  But it would get the dist's tests passing in the meantime.

Update: added 33acbea.

**Comment by karenetheridge** [comment]
Is this issue still outstanding?

**Comment by mjgardner** [comment]
I'm marking this as fixed for now and going to do a new release. It's way overdue.

**Comment by rehsack** [comment]
On 17.05.13 16:25, Mark Gardner wrote:

> I'm marking this as fixed for now and going to do a new release. It's
> way overdue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mjgardner/moosex-app-cmd/issues/2#issuecomment-18064434.
> 
> Wow - no reaction and no patch applying for months and not able to wait 
> more than two weeks for a reaction?

Sorry folks ...

## Cheers

Jens Rehsack

**Comment by mjgardner** [comment]
Sorry, I've been busy with job changes and other life issues. Please open a new pull request against the current code if there's more to patch and I'll be happy to oblige.

**Comment by rehsack** [comment]
On 17.05.13 16:52, Mark Gardner wrote:

> Sorry, I've been busy with job changes and other life issues. Please
> open a new pull request against the current code if there's more to
> patch and I'll be happy to oblige.

Hey - I know what you mean: I have 2 children, my better half is working 
and I work around 250 hours a month (including those for
open source Perl and NetBSD).

That's what I mean - when don't hurrying - then be consequent :)

## Cheers

Jens Rehsack

**Comment by karenetheridge** [comment]
@rehsack if there was more to do in this issue, please say so. Otherwise, please cease using it as evidence that I have wronged you in some way.

**Comment by rehsack** [comment]
@karenetheridge - so you're permitted to tackle me being stubborn and arguing with me is waste of time and emotion, but when I remind you that our first encounter was vice versa and it continues being that way until nowadays (https://github.com/perl5-dbi/AnyData/pull/1) where PR's are submitted which won't do on 5.8 out of the box and don't get it ... come on, don't throw stones.

**Comment by karenetheridge** [comment]
@rehsack this was not a personal question. I am asking you if there is anything more to be done in this ticket. Can you please anwer?

**Comment by rehsack** [comment]
@karenetheridge - I'm sorry, I have no clue. Since it took that long, I completely switched to Moo/MooX::\* stuff

And my answer was regarding you're 2nd sentence:

> Otherwise, please cease using it as evidence that I have wronged you in some way.
