### ISSUE TITLE
Missing ;authordep for Pod::Weaver plugins

### ISSUE THREAD

**Issue by omega** [mjgardner/moosex-app-cmd#4]
While setting up a new perl environment, I tried to install from git (to get the fix for config integration). I ran into the following missing modules after doing `dzil authordeps`, namely some missing `Pod::Weaver` plugins:
- Pod::Weaver::Section::Support
- Pod::Weaver::Plugin::StopWords

They can be added to `dist.ini` with

```
;authordep Pod::Weaver::Plugin::StopWords
;authordep Pod::Weaver::Section::Support
```

**Comment by mjgardner** [comment]
Fixed in 23dc541dfa58da44ece73d64ab98e0c84b2469c6, thanks!
