### ISSUE TITLE
Installation fails on Mac OSX 10.8.3

### ISSUE THREAD

**Issue by ynonp** [mjgardner/moosex-app-cmd#5]
Installation fails due to unit test failure. Attached log file:

cpanm (App::cpanminus) 1.5007 on perl 5.014002 built for darwin-2level
Work directory is /Users/ynonperek/.cpanm/work/1366822504.23563
You have make /usr/bin/make
You have LWP 6.04
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
Searching MooseX::App::Cmd on cpanmetadb ...
--> Working on MooseX::App::Cmd
Fetching http://search.cpan.org/CPAN/authors/id/M/MJ/MJGARDNER/MooseX-App-Cmd-0.09.tar.gz
-> OK
Unpacking MooseX-App-Cmd-0.09.tar.gz
Entering MooseX-App-Cmd-0.09
Checking configure dependencies from META.yml
Checking if you have ExtUtils::MakeMaker 6.30 ... Yes (6.62)
Configuring MooseX-App-Cmd-0.09
Running Makefile.PL
Checking if your kit is complete...
Looks good
Writing Makefile for MooseX::App::Cmd
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have warnings 0 ... Yes (1.12)
Checking if you have base 0 ... Yes (2.16)
Checking if you have Test::Requires 0 ... Yes (0.06)
Checking if you have Scalar::Util 0 ... Yes (1.23)
Checking if you have YAML 0 ... Yes (0.80)
Checking if you have MooseX::ConfigFromFile 0 ... Yes (0.10)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.62)
Checking if you have Data::Dumper 0 ... Yes (2.130_02)
Checking if you have Carp 0 ... Yes (1.26)
Checking if you have strict 0 ... Yes (1.04)
Checking if you have Test::More 0.94 ... Yes (0.98)
Checking if you have File::Find 0 ... Yes (1.19)
Checking if you have File::Temp 0 ... Yes (0.22)
Checking if you have Test::Output 0 ... Yes (1.01)
Checking if you have English 0 ... Yes (1.04)
Checking if you have App::Cmd 0.3 ... Yes (0.320)
Checking if you have MooseX::Has::Options 0 ... Yes (0.003)
Checking if you have MooseX::Getopt 0.18 ... Yes (0.56)
Checking if you have App::Cmd::Command 0 ... Yes (0.320)
Checking if you have Test::use::ok 0 ... Yes (0.02)
Checking if you have File::Basename 0 ... Yes (2.82)
Checking if you have Getopt::Long::Descriptive 0.091 ... Yes (0.091)
Checking if you have MooseX::MarkAsMethods 0 ... Yes (0.15)
Checking if you have Moose 0.86 ... Yes (2.0801)
Checking if you have Moose::Object 0 ... Yes (2.0801)
Building and testing MooseX-App-Cmd-0.09
cp lib/MooseX/App/Cmd.pm blib/lib/MooseX/App/Cmd.pm
cp lib/MooseX/App/Cmd/Command.pm blib/lib/MooseX/App/Cmd/Command.pm
Manifying blib/man3/MooseX::App::Cmd.3
Manifying blib/man3/MooseX::App::Cmd::Command.3
PERL_DL_NONLAZY=1 /Users/ynonperek/perl5/perlbrew/perls/perl-5.14.2/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t ............... ok
# Testing with Perl 5.014002, /Users/ynonperek/perl5/perlbrew/perls/perl-5.14.2/bin/perl
# App::Cmd version is 0.320
# App::Cmd::Command version is 0.320
# Carp version is 1.26
# Data::Dumper version is 2.130_02
# English version is 1.04
# ExtUtils::MakeMaker version is 6.62
# File::Basename version is 2.82
# File::Find version is 1.19
# File::Temp version is 0.22
# Getopt::Long::Descriptive version is 0.091
# Moose version is 2.0801
# Moose::Object version is 2.0801
# MooseX::ConfigFromFile version is 0.10
# MooseX::Getopt version is 0.56
# MooseX::Has::Options version is 0.003
# MooseX::MarkAsMethods version is 0.15
# Scalar::Util version is 1.23
# Test::More version is 0.98
# Test::Output version is 1.01
# Test::Requires version is 0.06
# Test::use::ok version is 0.02
# YAML version is 0.80
# base version is 2.16
# strict version is 1.04
# warnings version is 1.12

t/000-report-versions.t ...... ok
t/author-critic.t ............ skipped: these tests are for testing by the author
t/author-test-eol.t .......... skipped: these tests are for testing by the author
t/basic.t .................... ok
t/build_emulates_new.t ....... ok
# Failed test 'command died with the correct string'
# at t/configfile.t line 30.
# 'Can't call method "can" on an undefined value at /Users/ynonperek/perl5/modules/lib/perl5/MooseX/ConfigFromFile.pm line 28.
# '
# doesn't match '(?^:Mandatory parameter 'moo' missing in call to (eval))'
# Looks like you failed 1 test of 3.

t/configfile.t ............... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
t/release-cpan-changes.t ..... skipped: these tests are for release candidate testing
t/release-dist-manifest.t .... skipped: these tests are for release candidate testing
t/release-distmeta.t ......... skipped: these tests are for release candidate testing
t/release-kwalitee.t ......... skipped: these tests are for release candidate testing
t/release-meta-json.t ........ skipped: these tests are for release candidate testing
t/release-minimum-version.t .. skipped: these tests are for release candidate testing
t/release-mojibake.t ......... skipped: these tests are for release candidate testing
t/release-no-tabs.t .......... skipped: these tests are for release candidate testing
t/release-pod-coverage.t ..... skipped: these tests are for release candidate testing
t/release-pod-linkcheck.t .... skipped: these tests are for release candidate testing
t/release-pod-syntax.t ....... skipped: these tests are for release candidate testing
t/release-portability.t ...... skipped: these tests are for release candidate testing
t/release-synopsis.t ......... skipped: these tests are for release candidate testing
t/release-test-version.t ..... skipped: these tests are for release candidate testing
t/release-unused-vars.t ...... skipped: these tests are for release candidate testing
## Test Summary Report

t/configfile.t             (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=22, Tests=43,  3 wallclock secs ( 0.08 usr  0.04 sys +  2.62 cusr  0.20 csys =  2.94 CPU)
Result: FAIL
Failed 1/22 test programs. 1/43 subtests failed.
make: **\* [test_dynamic] Error 255
-> FAIL Installing MooseX::App::Cmd failed. See /Users/ynonperek/.cpanm/build.log for details.

**Comment by mjgardner** [comment]
This is the same bug as #3.
