### ISSUE TITLE
improve integration with MooseX::SimpleConfig

### ISSUE THREAD

**Issue by abraxxa** [mjgardner/moosex-app-cmd#6]
While looking for a way to populate command attributes from a config file I've read the code at https://metacpan.org/source/MJGARDNER/MooseX-App-Cmd-0.10/lib/MooseX/App/Cmd/Command.pm#L44 to find out that support for that exists but is entirely undocumented.
I've added MooseX::SimpleConfig to my command class and followed its docs by specifying the config file path using has '+configfile' => ( default => '/etc/myapp.conf' ); just to find out that it's ignored.
I then changed it to sub _get_default_configfile { return '/etc/myapp.conf'; } which works.
Please change the code and docs to show the usage with MooseX::SimpleConfig instead of this undocumented behaviour, thanks!

**Comment by mjgardner** [comment]
Added documentation in 2b1698965812ee686feba901851db0a5fc347743, hope this helps

**Comment by abraxxa** [comment]
Thanks, but why does '+configfile' => ( default => '/etc/myapp.conf' ); fail?
