### ISSUE TITLE
t/basic.t FAILs

### ISSUE THREAD

**Issue by DannyThomas** [mjgardner/moosex-app-cmd#7]
perl 5.16.3, RHEL6, MooseX-App-Cmd-0.10

t/000-report-versions.t ...... 1/? #     App::Cmd version is 0.322
# App::Cmd::Command version is 0.322
# Carp version is 1.26
# Data::Dumper version is 2.135_06
# English version is 1.05
# ExtUtils::MakeMaker version is 6.82
# File::Basename version is 2.84
# File::Find version is 1.20
# File::Temp version is 0.22
# Getopt::Long::Descriptive version is 0.096
# Moose version is 2.1005
# Moose::Object version is 2.1005
# MooseX::ConfigFromFile version is 0.12
# MooseX::Getopt version is 0.58
# MooseX::Has::Options version is 0.003
# MooseX::MarkAsMethods version is 0.15
# Scalar::Util version is 1.35
# Test::More version is 0.98
# Test::Output version is 1.01
# Test::use::ok version is 0.11
# YAML version is 0.84
# base version is 2.18
# strict version is 1.07
# warnings version is 1.13

t/000-report-versions.t ...... ok  
t/author-critic.t ............ skipped: these tests are for testing by the author
t/author-test-eol.t .......... skipped: these tests are for testing by the author
t/basic.t .................... 1/12 
# Failed test 'got correct list of registered command names'
# at t/basic.t line 16.
# Structures begin differing at:
# $got->[1] = '--version'
# $expected->[1] = '-?'
# Failed test 'got correct list of registered command plugins'
# at t/basic.t line 26.
# Structures begin differing at:
# $got->[2] = 'App::Cmd::Command::version'
# $expected->[2] = 'Test::MyCmd::Command::bark'
# Looks like you failed 2 tests of 12.

**Comment by mjgardner** [comment]
Fixed by merging @ubermichael's pull request into 5446b00. Thanks for the report!
